language: csharp
solution: TestClass.sln
notifications:
email:
recipients:
- khanhduyluu@gmail.com
- tuankiet234@gmail.com
- ttkk.ben10@yahoo.com.vn
on_success: [always|never|change] # default: always
on_failure: [always|never|change] # default: always
install:
  - nuget restore TestClass/TestClass.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TestClass/TestClass.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TestClass/TestClass/bin/Release/TestClass.dll