language: csharp
solution: DemoTravisCI 2.sln
notifications:
email:
recipients:
- tuankiet234@gmail.com
- ttkk.ben10@yahoo.com.vn
- khanhduyluu@gmail.com
on_success: [always|never|change] # default: always
on_failure: [always|never|change] # default: always
install:
  - nuget restore DemoTravisCI 2.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug DemoTravisCI 2.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DemoTravisCI 2/DemoTravisCI 2/bin/Debug/DemoTravisCI 2.dll